### ISSUE TITLE
Latest not working on 2.77+

### ISSUE THREAD

**Issue by Vicousvern** [niacdoial/blemd#33]
Hi, love the idea of this tool, I'm so eager to actually use it, espesially since maxBMD doesn't work either. Upon importing any bdl from WindWaker it causes Belnder to softlock and become unresponsive. I've tested on 2.77 and 2.79 so far and exactly the same.

I did however download the Nov 4, 2018 commit (Another handful of bugfixes plus a small feature) which does work in Blender 2.77. It properly imported the bdl and bck animation which is perfect.

**Comment by ajd-262** [comment]
I have 2.78 and do find a copy from early 2018 seems to work when the newer version I have fails. Remember bdl support is limited. If all else fails try a copy of BMDView2.

**Comment by Avatarus-one** [comment]
So, it's not just me. I tried to import few ZTP levels with 2.79 and it didn't work. Blender stopped responding and occupied all the memory in few minutes.

**Comment by ajd-262** [comment]
Stages seem to be unstable when imported. Best to export them out of Blender as .dae or .obj soon as possible.

**Comment by niacdoial** [comment]
oh. I didn't notice the replies before answering the mail notification.
The first half of my answer will probably look dumb then. ...answer which isn't even here, it seems

**Comment by Vicousvern** [comment]
I only needed Link and all his animations for a uni project and managed to get those thankfully using 2.77 and the older commit. Just thought I'd raise an issue incase it wasn't aware or I was doing something wrong.
Either way I'm grateful I managed to get what I needed, thank you.

**Comment by niacdoial** [comment]
I definitely wasn't aware of the new version hanging somewhere. Thanks!
...and since you have what you want, the answer I sent by mail is definitely out of date. yay. (basically, it was asking you to run the import process from the command line with an extra python file, and send me the logs)

**Comment by Vicousvern** [comment]
I'm completely new to Blender, first thing I did was export to fbx so I can work in Max! But if you give me instructions I'll gladly help out, least I can do in return.

**Comment by niacdoial** [comment]
OK.
since the mail answer probably won't arrive for a few hours,  here's a copy of the instructions.

- download this file. It's an updated version of a script that's already on this repo. (put it anywhere, it doesn't matter).
- open a command prompt (windows+r, then type "cmd" and enter)
- type the line `"path\to\blender" -b -P "path\to\IOmanager.py" "\path\to\your\file.bdl"` (after editing the paths). It asks blender to run without a window, and it asks it to run the python script immediately. The script just imports the bdl file and exports a fbx file.
- when you feel it ran for too long, press Ctrl+C (then a second time if it doesn't work) to stop it
- send me a text copy (or screenshot) of what got written when blender was running (you can edit it to remove your username, of course)

thanks!

**Comment by Vicousvern** [comment]
> download this file.

Which file? I've waited to see if it shows up in my email but nothing. email me direct if you like @hotmail dot com with the file you want me to try.

**Comment by niacdoial** [comment]
I.... legit forgot to include it. My bad. here.
https://lufi.ethibox.fr/r/nB7SqK1X#/NH6Xz+odGHTtlyL1Os5RVxzEMm8IMg9gLXDI7WFtrc=

**Comment by Vicousvern** [comment]
I went to try this now and the file no longer exists! Want me to just provide you with the logs from the latest commit, or does it have to be your updated file?

**Comment by niacdoial** [comment]
I mean, the logs alone should be enough, as long as you know how much is already written when it hangs.
I thought that by using launching blender that way and using ctrl+C, it would actually send the interruption to python, which would in turn tell exactly where it was when the interruption happened.
Here's a new link (it should take a week to expire, not 24h like the old one)
https://file.lesamarien.fr/lufi/r/WAqR8Q5V0F#sSKFmhU0DbrKhP7t/jyaUau7hJnZGqfEzh05pnheo9c=
sorry for taking so long to get everything right...

**Comment by Vicousvern** [comment]
Sorry for the delay, I tried to get the file you linked at the time you posted but it was invalid again and didnt want to bother you any more. I decided to get the latest and get a log for you.

C:\Users\vicou>"C:\Program Files\Blender Foundation\Blender\blender.exe" -b -P "C:\Program Files\Blender Foundation\Blender\2.77\scripts\addons_contrib\blemd\automated-converter\IOmanager.py" "C:\Users\vicou\Desktop\LinkConverted\bmd\cl\cl.bdl"
Read new prefs: C:\Users\vicou\AppData\Roaming\Blender Foundation\Blender\2.77\config\userpref.blend
found bundled python: C:\Program Files\Blender Foundation\Blender\2.77\python
blemd
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "C:\Program Files\Blender Foundation\Blender\2.77\scripts\addons_contrib\blemd\automated-converter\IOmanager.py", line 5, in <module>
    bpy.data.objects.remove(bpy.data.objects['Cube'],True)
TypeError: BlendDataObjects.remove(): takes at most 1 arguments, got 2
Error: File format is not supported in file 'C:\Users\vicou\Desktop\LinkConverted\bmd\cl\cl.bdl'

This is trying to load Link, I've tried with a postbox and other stuff and the same. It doesnt hang using the command line, but if I import the same Link (cl.cdl) file in Blender it softlocks.

Hope this helps, I'm happy to do anything else you may need, The older commit still works for most files, but even that hangs on some models too.

**Comment by niacdoial** [comment]
OK, thanks, but... this version of `IOmanager.py` is broken and has been for a few commits now...
that's the only infor in this error message, sadly.
I'll try to put the newer version (the one that actually works) in, next commit.
Again, sorry.

**Comment by Vicousvern** [comment]
It's absolutely fine, I appreciate your work regardless. If you Dropbox the file I'll do a new log for you. 
If it weren't for needing the animations I'd use BMDview2 to export. If you manage to get this working with more models I'll happily buy you a beer / coffee 👍

**Comment by Avatarus-one** [comment]
Never use BMDView2 to export anything, except dds textures. It comes with messed up texture names on 3ds export, damaging dds->tga conversion, missing bones and animations, missing vertex colors, missing UV maps except UV1, which may become partially downscaled if there are mirrored textures in the model.

**Comment by Vicousvern** [comment]
I did noticed exports from BMDview were not ideal. It's ok for use as placeholders as I can remodel and texture, but like you said no bones or animations which for my use would save soo much time!

Is there any other reliable way of exporting models with animations?

**Comment by Avatarus-one** [comment]
The most reliable tools are BleMD and MaxBMD. But the second one cannot export additional UVs either. I cannot figure out how to fix it.

**Comment by Vicousvern** [comment]
I tried MaxBMD as I use Max primarily but I couldn't get it to work on the latest. Any way around this do you know as I'd like to use that too alongside blemd.

**Comment by Avatarus-one** [comment]
Okay, let's continue this in MaxBMD repo. I didn't install it on versions above 2016. Can you describe the problem? Is there an error or something?

**Comment by Vicousvern** [comment]
Sure I'll open an issue in a minute. Apologies niacdoial for the message spams!

**Comment by Mootook** [comment]
For anyone stumbling, I used https://github.com/niacdoial/blemd/tree/0d618dd6743b7fc3edefe47777fee855f6335531 instead as the Blender add-on (2.77).
Curious what it major changes required to get it working on latest stable Blender? API has changed too much?

**Comment by niacdoial** [comment]
I mean, it should be possible to adapt it pretty easily, but…
tbh I don't have nearly as much time/will for this project as I used to.
heck, blender 2.8x is not event the first element on my todolist for this project. I honestly want to rework the IO part (again) and add better in-code documentation first.

**Comment by niacdoial** [comment]
Given what I'm seeing, I'll have to assume things were fixed since the last message.
feel free to reopen if I'm wrong
