### ISSUE TITLE
When I attempt to enable the addon in Blender, I get this error:

### ISSUE THREAD

**Issue by altprogrammer** [niacdoial/blemd#6]
Traceback (most recent call last):
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\2.78\scripts\modules\addon_utils.py", line 330, in enable
    mod = __import__(module_name)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\2.78\scripts\addons_contrib\blemd-master\__init__.py", line 15, in <module>
    from .BModel import BModel
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\2.78\scripts\addons_contrib\blemd-master\BModel.py", line 17, in <module>
    MModule = import_module('.Matrix44', "blemd")
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\2.78\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 981, in _gcd_import
  File "<frozen importlib._bootstrap>", line 931, in _sanity_check
SystemError: Parent module 'blemd' not loaded, cannot perform relative import

**Comment by altprogrammer** [comment]
I tried using normal Blender, but I got the same error:

AL lib: (EE) UpdateDeviceParams: Failed to set 44100hz, got 48000hz instead
found bundled python: C:\Program Files\Blender Foundation\Blender\2.78\python
reloading addon: blemd-master 1497478932.6213627 1497481697.8504083 C:\Users\Aiden\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\blemd-master\__init__.py
Modules Installed from 'C:\\Users\\Aiden\\Downloads\\blemd-master.zip' into 'C:\\Users\\Aiden\\AppData\\Roaming\\Blender Foundation\\Blender\\2.78\\scripts\\addons' ()
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.78\scripts\modules\addon_utils.py", line 330, in enable
    mod = __import__(module_name)
  File "C:\Users\Aiden\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\blemd-master\__init__.py", line 15, in <module>
    from .BModel import BModel
  File "C:\Users\Aiden\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\blemd-master\BModel.py", line 17, in <module>
    MModule = import_module('.Matrix44', "blemd")
  File "C:\Program Files\Blender Foundation\Blender\2.78\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 981, in _gcd_import
  File "<frozen importlib._bootstrap>", line 931, in _sanity_check
SystemError: Parent module 'blemd' not loaded, cannot perform relative import

**Comment by niacdoial** [comment]
Er...
I think you made a couple mistakes, but that probably just means I wasn't
precise enough in the docs.
Here are a couple tips to fix it:
- the folder containing the add-on MUST be called "blemd", because the
folder name is referenced by the relative import procedure,
so rename the zip folder "blemd.zip" before installing


-if that fails, then correct the following yourself (in the addons\ or
addons_contrib\  folder)
move "blemd-master_init_.py" into the "blemd" folder as "__init__.py" (with
two underscores on each end)

Hope that fixes it.
Will add that to the docs... soon?
Anyways, have a nice day.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-06-15 1:10 GMT+02:00 altprogrammer <notifications@github.com>:

**Comment by niacdoial** [comment]
Is the problem fixed? (lack of answer will be taken as yes and issue will be closed untill further notice)

**Comment by niacdoial** [comment]
`issue assumed fixed`
