### ISSUE TITLE
Import not working.

### ISSUE THREAD

**Issue by Sir-LoLz** [niacdoial/blemd#84]
Using blender 3.5. When i try to import a model from pikmin 2 I get this error.

![image](https://github.com/niacdoial/blemd/assets/55112620/544a960c-b393-452f-b965-5d8a3d5e76ce)

**Comment by niacdoial** [comment]
If I'm right about what caused this, you should be able to import without crashing, but there will be some missing geometry.
you should also have an error message starting with "Unknown primitive type" for every piece of missing geometry (you can see it if you show the terminal that runs blender. I think the option to show it is somewhere in the "Window" menu)
Could you tell me what they say, please?

**Comment by Sir-LoLz** [comment]
`Read prefs: C:\Users\Zach\AppData\Roaming\Blender Foundation\Blender\3.5\config\userpref.blend
Info: Deleted 3 object(s)

F:\games\gamecube roms\pikmin 2 battle\files\player\garf\model.bmd
2024-04-07 20:06:33,759    DEBUG bpy.ops.import_mesh.bmd.main Started import section: Load
INF 1
VTX 1
2024-04-07 20:06:33,962     INFO bpy.ops.import_mesh.bmd.vtx1 amount of position coordinates (4072) is not //3
2024-04-07 20:06:33,967     INFO bpy.ops.import_mesh.bmd.vtx1 length of normal coordinates (4080) is not //3
EVP 1
DRW 1
JNT 1
SHP 1
MAT 3
off[1](raw): 6 vs 3
off[4]: 1.0
off[5]: 2.0 (4)
off[6]: 4 (1)
off[7]: 6.0 (8)
off[8]: 2.0 (4)
off[0](raw): 996 vs 3
off[3]: 3.0 (312)
off[10]: 4 (1)
off[11]: 2.0 (4)
off[12]: 0.0 (4)
off[13]: 2.0 (100)
2024-04-07 20:06:34,078     INFO bpy.ops.import_mesh.bmd.matv2 (mat3texmtx) 101 instead of 0x0100
off[15]: 2.0 (2)
TEX 1
2024-04-07 20:06:34,078    DEBUG bpy.ops.import_mesh.bmd.main ExtractImages function called
2024-04-07 20:06:34,143    DEBUG bpy.ops.import_mesh.bmd.main Decided to actually extract images
C:\Users\Zach\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blemd\bmdview.exe
F:\games\gamecube roms\pikmin 2 battle\files\player\garf\model.bmd
F:\games\gamecube roms\pikmin 2 battle\files\player\garf\model_bmd\Textures
TGA
textures: F:\games\gamecube roms\pikmin 2 battle\files\player\garf\model_bmd\Textures\
Read INF1
Read VTX1
Read EVP1
Read DRW1
Read JNT1
Read SHP1
Read MAT3
Read TEX1

Image names:
2024-04-07 20:06:34,208    DEBUG bpy.ops.import_mesh.bmd.main Finished extracting images
2024-04-07 20:06:34,209    DEBUG bpy.ops.import_mesh.bmd.main Started import section: DrawScene
2024-04-07 20:06:34,210    DEBUG bpy.ops.import_mesh.bmd.main frame node created
2024-04-07 20:06:34,210    DEBUG bpy.ops.import_mesh.bmd.main Started imprort section: DrawScenegraph
2024-04-07 20:06:34,210    DEBUG bpy.ops.import_mesh.bmd.main Started imprort section: DrawScenegraph
2024-04-07 20:06:34,212  WARNING bpy.ops.import_mesh.bmd.texhelper Problem with image F:\games\gamecube roms\pikmin 2 battle\files\player\garf\model_bmd\Textures\orima_565.tga (error is Error: Cannot read 'F:\games\gamecube roms\pikmin 2 battle\files\player\garf\model_bmd\Textures\orima_565.tga': No such file or directory
)
2024-04-07 20:06:34,213    ERROR bpy.ops.import_mesh.bmd.main node (GLSL) materials went wrong.Falling back to incomplete materials.(error is Error: Cannot read 'F:\games\gamecube roms\pikmin 2 battle\files\player\garf\model_bmd\Textures\orima_565.tga': No such file or directory
)
2024-04-07 20:06:34,214  WARNING bpy.ops.import_mesh.bmd.texhelper Problem with image F:\games\gamecube roms\pikmin 2 battle\files\player\garf\model_bmd\Textures\orima_565.tga (error is Error: Cannot read 'F:\games\gamecube roms\pikmin 2 battle\files\player\garf\model_bmd\Textures\orima_565.tga': No such file or directory
)
2024-04-07 20:06:34,214    ERROR bpy.ops.import_mesh.bmd.main Material not built correctly (error is Error: Cannot read 'F:\games\gamecube roms\pikmin 2 battle\files\player\garf\model_bmd\Textures\orima_565.tga': No such file or directory
)
2024-04-07 20:06:34,215    DEBUG bpy.ops.import_mesh.bmd.main Started imprort section: DrawScenegraph
2024-04-07 20:06:34,234  WARNING bpy.ops.import_mesh.bmd.main Unknown primitive 144
2024-04-07 20:06:34,235 CRITICAL bpy.ops.import_mesh.bmd.main Mesh description in scene graph is nonsensical. (error is local variable 'iterator' referenced before assignment)
2024-04-07 20:06:34,235 CRITICAL bpy.ops.import_mesh.bmd An error happened. If it wasn't reported before, here it is: local variable 'iterator' referenced before assignment
Traceback (most recent call last):
  File "C:\Users\Zach\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blemd\__init__.py", line 228, in execute
    temp.Import(fname, **{x: getattr(self, x) for x in self.ALL_PARAMS})
  File "C:\Users\Zach\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blemd\BModel.py", line 1038, in Import
    self.DrawScene()
  File "C:\Users\Zach\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blemd\BModel.py", line 788, in DrawScene
    self.DrawScenegraph(sg, i)
  File "C:\Users\Zach\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blemd\BModel.py", line 741, in DrawScenegraph
    self.DrawScenegraph(com, effP, onDown, matIndex)  # -- note: i and j start at 1 instead of 0
  File "C:\Users\Zach\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blemd\BModel.py", line 741, in DrawScenegraph
    self.DrawScenegraph(com, effP, onDown, matIndex)  # -- note: i and j start at 1 instead of 0
  File "C:\Users\Zach\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blemd\BModel.py", line 738, in DrawScenegraph
    self.DrawBatch(n.index, matIndex)  # fixed
  File "C:\Users\Zach\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blemd\BModel.py", line 503, in DrawBatch
    for p0, p1, p2 in iterator:
UnboundLocalError: local variable 'iterator' referenced before assignment`
