### ISSUE TITLE
Trying to export a BCK gives me a Python: Traceback error

### ISSUE THREAD

**Issue by SuperNoahPlushes** [niacdoial/blemd#85]
`Python: Traceback (most recent call last):`
`File "D:\blender 3\3.0\scripts\addons_contrib\blemd\__init__.py", line 658, in execute`
`ex_bck.dump_action(out_action, anim_armature.pose)`
`AttributeError: 'NoneType' object has no attribute 'pose'`

`location: <unknown location>:-1`

any idea why this happens?

what it looks like in blender (3.0.1)
![blender_kJriagfPVc](https://github.com/niacdoial/blemd/assets/89299730/002af55d-65f3-4a49-bfcf-dd79167384da)

the error (twice)
![blender_G6U6yYIoJq](https://github.com/niacdoial/blemd/assets/89299730/a59c09f8-d6ec-40ea-9aa7-abe90ca43428)

the animation working in blender
https://github.com/niacdoial/blemd/assets/89299730/df9c904e-6ab9-4e66-9cce-0bf95f1766ea

(its a bit dinky looking but thats not what this is about lmao)

**Comment by niacdoial** [comment]
question: when the select-file-to-save-to window popped up, was there a panel on the right with three dropdowns (Mode, Armatures and Actions)?
if it did, what did the contents of the dropdowns look like?

**Comment by Gel-lambar** [comment]
Hello im having the same problem and im seeing this didn't get a response so i want to know what to do in the same scenario
![error](https://github.com/user-attachments/assets/9437b1fb-5b12-42e4-adcb-87a3ee2de74b)

This is how the panel in the right looks like
![error1](https://github.com/user-attachments/assets/5295346c-0211-4fb9-90fd-8d2c03a2a530)

**Comment by Syreyup** [comment]
hi idk what yall did in the past but it works now, perfectly, like it just works

https://github.com/user-attachments/assets/ccbdfad9-d054-421f-9d1e-7e7eb616d840

thank you

**Comment by Syreyup** [comment]
update, it works sometimes? now it doesn't but i didn't do anything differently than the last time it did work.


`Python: Traceback (most recent call last):
  File "C:\Users\Noah\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blemd-master\__init__.py", line 658, in execute
    ex_bck.dump_action(out_action, anim_armature.pose)
  File "C:\Users\Noah\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blemd-master\Bck.py", line 340, in dump_action
    self.process_translation_track(trans_fcurves, f, joint_anim, local_rotation, local_matrix)
  File "C:\Users\Noah\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blemd-master\Bck.py", line 424, in process_translation_track
    value, handle_left, handle_right = self.get_track_keyframe(x_track, y_track, z_track, frame)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noah\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blemd-master\Bck.py", line 355, in get_track_keyframe
    (x_co, x_handle_left, x_handle_right) = self.get_key_value(x_curve, frame)
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noah\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blemd-master\Bck.py", line 347, in get_key_value
    keyframe = next((k for k in curve.keyframe_points if k.co[0] == frame), None)
                                ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'keyframe_points'`

![Image](https://github.com/user-attachments/assets/855a5c0f-68d8-4a2c-a101-4f9be55a557e)

![Image](https://github.com/user-attachments/assets/3d11ed61-86f0-4c9d-9f62-016e0180cc7b)

**Comment by CasiniLoogi** [comment]
I, too, am having a similar issue. I have a single bone in an armature with a simple spinning animation; I'm not sure if I could get any simpler. The script throws
```
Python: Traceback (most recent call last):
  File "C:\Users\Francisco\AppData\Roaming\Blender Foundation\Blender\4.4\scripts\addons\blemd-master\__init__.py", line 658, in execute
    ex_bck.dump_action(out_action, anim_armature.pose)
                                   ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'pose'
```
when trying to export the bck.
